// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using panda4.Models;

namespace panda4.Data.Migrations
{
    [DbContext(typeof(KomputerContext))]
    [Migration("20200201222550_Komputer")]
    partial class Komputer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("panda4.Models.KomputerModel", b =>
                {
                    b.Property<int>("KomputerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cena");

                    b.Property<DateTime>("DataProdukcji");

                    b.Property<string>("KartaGraficzna");

                    b.Property<string>("Model");

                    b.Property<string>("PlytaGlowna");

                    b.Property<string>("Procesor");

                    b.Property<string>("Producent");

                    b.HasKey("KomputerID");

                    b.ToTable("Komputer");
                });

            modelBuilder.Entity("panda4.Models.OcenaModel", b =>
                {
                    b.Property<int>("OcenaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KomputerID");

                    b.Property<int>("Ocena");

                    b.HasKey("OcenaID");

                    b.ToTable("Ocena");
                });

            modelBuilder.Entity("panda4.Models.RezerwacjaModel", b =>
                {
                    b.Property<int>("RezerwacjaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPrzedluzona");

                    b.Property<DateTime>("DataRozpoczecia");

                    b.Property<DateTime>("DataZakonczenia");

                    b.Property<int>("KomputerID");

                    b.Property<int>("UzytkownikID");

                    b.HasKey("RezerwacjaID");

                    b.ToTable("Rezerwacja");
                });

            modelBuilder.Entity("panda4.Models.UzytkownicyModel", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CzyAdmin");

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<int>("Wypozyczone");

                    b.HasKey("UzytkownikId");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("panda4.Models.ZnizkiModel", b =>
                {
                    b.Property<int>("ZnizkiId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UzytkownikId");

                    b.Property<int>("Znizka");

                    b.HasKey("ZnizkiId");

                    b.ToTable("Znizki");
                });
#pragma warning restore 612, 618
        }
    }
}
